### PR TITLE
All supporting packages with its null-safe version.

### LINKED ISSUE #70: Implementing Null-Safety
## Expected Behavior
Ability to use kuzzle flutter package as a null-safety package.

## Current Behavior
Impossible to use with sound null-safety.

## Possible Solution
Create a null-safe package as with [instructions here](https://flutter.dev/docs/null-safety).

## Steps to Reproduce
After following [these steps](https://dart.dev/null-safety/migration-guide) and having included all null-safety packages, kuzzle flutter will fail.

## Context (Environment)
Since Flutter is almost ready to transfer to stable with full null-safety capabilities, it will be great for the kuzzle project to get receive the expose it deserves by being null-safe ready. I attest to this projects quality but it completely lacks the attention it deserves. It is really a great alternative to many paid projects. It being null-safe people will trust its maintainability. Also, I want to use it in a null-safe project and this is the last package incompatible. If I have time I will start converting and doing pull requests.

### PR DESCRIPTION
**Pull request by TitanKing**
This is the first step (supporting sound-null safe) packages to address this issue #70. All supporting packages are marked stable.

### CODE REVIEW

**Comment by jenow** [comment]
I think we should create another branch to deploy the null safety version as prerelease on pub.dev

**Comment by TitanKing** [comment]
It would be better to create another branch to fix this in. I looked through the flutter client and it is NOT going to be a massive pain to make it null safe.

**Comment by jenow** [comment]
> It would be better to create another branch to fix this in. I looked through the flutter client and it is NOT going to be a massive pain to make it null safe.

I agree but we have to keep the non null safe version for projects which does not use the null safe version of Dart.

**Comment by TitanKing** [comment]
Yes, there will have to be two versions. If you could create a branch, I will start working on it if someone from the team can't jump on it.

**Comment by jenow** [comment]
> Yes, there will have to be two versions. If you could create a branch, I will start working on it if someone from the team can't jump on it.

Done: `null-safety`

**Comment by jenow** [comment]
https://github.com/kuzzleio/sdk-dart/releases/tag/3.0.0

**Pull request closed without merging**
